### ISSUE TITLE
Add artifacts registry for a4c plugins in README.md

### ISSUE THREAD

**Issue by billmetangmo** [ystia/yorc-a4c-plugin#22]
# Issue Type

Put an X between the brackets of the corresponding issue type

* [ ] Bug report
* [X] Documentation issue report
* [ ] Improvement request

## Description
Add the link to distrib files: https://bintray.com/ystia/yorc-a4c-plugin/distributions

So that we can easily download yorc a4c plugin.

**Comment by loicalbertin** [comment]
Now done using badges and a specific section in readme
