### ISSUE TITLE
Upgrade to Alien Kubernetes plugin 2.1-Mx

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc-a4c-plugin#50]
**As:** Yorc team
**I want to:** upgrade to a4c Kubernetes plugin 2.1
**So that:** I can benefit from newest features like jobs support we introduced recently

**Comment by adidanes** [comment]
The Alien Kubernetes plugin evolves and support additional K8S resource types. Among them, the Job types are needed by the Yorc issue on K8S Jobs support : https://github.com/ystia/yorc/issues/86.
We hope Job resource types will be included in Alien 2.1.0-SM7.

**Comment by adidanes** [comment]
Upgraded to Alien 2.1.0-SM7

**Comment by loicalbertin** [comment]
Done as per #69
